language: java
jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2"

services:
  - docker

before_install:
  - docker pull oracle/graalvm-ce:1.0.0-rc16
  - docker pull frolvlad/alpine-glibc

jobs:
  include:
    - stage: build
      name: "akkahttp"
      script:
        - cd akkahttp
        - mvn -U clean install
    - stage: build
      name: "armeria"
      script:
        - cd armeria
        - mvn -U clean install
    - stage: build
      name: "dropwizard"
      script:
        - cd dropwizard
        - mvn -U clean install
    - stage: build
      name: "sparkjava"
      script:
        - cd sparkjava
        - mvn -U clean install
    - stage: build
      name: "undertow"
      script:
        - cd undertow
        - mvn -U clean install
    - stage: build
      name: "webflux"
      script:
        - cd webflux
        - mvn -U clean install
