language: python

services:
  - docker

before_install:
  - docker pull maven:3.6.0-jdk-8-alpine
  - docker pull oracle/graalvm-ce:1.0.0-rc11
  - docker pull frolvlad/alpine-glibc

jobs:
  include:
    - stage: build
      name: "Undertow"
      script:
        - cd undertow
        - docker build . -t devinsba/hello-world-nativeimages:undertow
        - docker run -d -p 8080:8080 devinsba/hello-world-nativeimages:undertow
        - curl http://localhost:8080
