language: python

services:
  - docker

before_install:
  - docker pull maven:3.6.0-jdk-8-alpine
  - docker pull oracle/graalvm-ce:1.0.0-rc11
  - docker pull frolvlad/alpine-glibc

jobs:
  include:
    - stage: build
      name: "Undertow"
      script:
        - cd undertow
        - docker build . -t devinsba/hello-world-nativeimages:undertow
        - docker run -d --name=undertow -p 8080:8080 devinsba/hello-world-nativeimages:undertow
        - curl http://localhost:8080
        - docker stop undertow
        - docker rm undertow
      after_failure:
        - docker logs undertow
    - stage: build
      name: "Dropwizard"
      script:
        - cd dropwizard
        - docker build . -t devinsba/hello-world-nativeimages:dropwizard
        - docker run -d --name=dropwizard -p 8080:8080 devinsba/hello-world-nativeimages:dropwizard
        - curl http://localhost:8080
        - docker stop dropwizard
        - docker rm dropwizard
      after_failure:
        - docker logs dropwizard
